name: vision-stretcher
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2021.4.0
  - ipykernel=6.13.0
  - ipython=8.3.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.0.6
  - jupyter_core=4.9.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.2
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - numba=0.55.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1n
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - prompt-toolkit=3.0.29
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.12.0
  - pyparsing=3.0.8
  - python=3.9.12
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pyzmq=19.0.2
  - readline=8.1.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tbb=2021.5.0
  - tk=8.6.11
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.2.0
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - black==21.4b2
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - detectron2==0.6+cu113
    - fonttools==4.33.3
    - future==0.18.2
    - fvcore==0.1.5.post20220414
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - hydra-core==1.1.2
    - idna==3.3
    - importlib-metadata==4.11.3
    - iopath==0.1.9
    - kiwisolver==1.4.2
    - markdown==3.3.6
    - matplotlib==3.5.2
    - mypy-extensions==0.4.3
    - oauthlib==3.2.0
    - omegaconf==2.1.2
    - opencv-python==4.5.5.64
    - pathspec==0.9.0
    - pip==22.0.4
    - portalocker==2.4.0
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pyyaml==6.0
    - regex==2022.4.24
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - tabulate==0.8.9
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - toml==0.10.2
    - tqdm==4.64.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - yacs==0.1.8
    - zipp==3.8.0
